@startuml
"Secretaria" as secetaria
"Aluno" as aluno
"Professor" as professor

secetaria --> (Gerenciar curriculo)
secetaria --> (Gerenciar informacoes)

(Gerenciar informacoes) <|-- (Gerenciar informacoes da disciplina)
(Gerenciar informacoes) <|-- (Gerenciar informacoes dos alunos)
(Gerenciar informacoes) <|-- (Gerenciar informacoes dos professores)

"Gerenciar curriculo de cada semestre" as (Gerenciar curriculo)
"Gerenciar informacoes" as (Gerenciar informacoes)
"Gerenciar informacoes da disciplina" as (Gerenciar informacoes da disciplina)
"Gerenciar informacoes dos professores" as (Gerenciar informacoes dos professores)
"Gerenciar informacoes dos alunos" as (Gerenciar informacoes dos alunos)

aluno --> (Matricular)
aluno --> (Cancelar matricula)
(Matricular) .> (Notificar cobranca) : include
(Matricular) .> (Validar disciplinas da matricula) : include
(Cancelar matricula) .> (Notificar cobranca) : include
"Matricular nas disciplinas" as (Matricular)
"Cancelar matricula" as (Cancelar matricula)
"Notificar sistema de cobranca" as (Notificar cobranca)
"Validar disciplinas da matricula" as (Validar disciplinas da matricula)

professor --> (Visualizar alunos da disciplina)
"Visualizar alunos da disciplina" as (Visualizar alunos da disciplina)


rectangle "Sistema" {
  "Validar quantidade de alunos no fim do semestre" as (Validar quantidade de alunos)
  "Cancelar disciplina" as (Cancelar disciplina)
   (Validar quantidade de alunos) <.. (Cancelar disciplina) : extends
}
@enduml
