@startuml
skinparam classAttributeIconSize 0

class Pessoa {
#id: String
#nome: String
#senha: String
#boolean login(String senha, String id)
}

Pessoa <|-- Secretaria
Pessoa <|-- Aluno
Pessoa <|-- Professor

class Secretaria {
+void gerarCurriculo()
+Curso cadastrarCurso()
}

class Aluno  {
-creditos: int
-curso: Curso
-turmas: List<Turma>
+void matricularDisciplinaObrigatoria(idDisciplina: int)
+void matricularDisciplinaOptativa(idDisciplina: int)
+void cancelarMatricula(idDisciplina: int)
}

class Professor  {
-List<Aluno> visualizarAlunosMatriculados()
}

class Curso {
-id: int
-nome: String
-CREDITOS: int {static}
-CARGA_HORARIA: int {static}
-disciplinas: List<Disciplina>
+ void adicionarDisciplina(disciplina: Disciplina)
+ void removerDisciplina(idDisciplina: int)
}

class Disciplina {
-id: int
-nome: String
-CREDITOS: int {static}
-CARGA_HORARIA: int {static}
-NUMERO_MAXIMO_ALUNOS: int {static}
-status: Status
-boolean validarNumeroMinimoDeAlunos()
-void cancelarDisciplina()
}

class Turma{
-professor: Professor
-disciplina: Disciplina
-alunos: List<Aluno>
+void adicionarAluno(aluno: Aluno)
+void removerAluno(aluno: Aluno)
+void selecionarProfessor(professor: Professor)
}

enum Status{
ATIVA
ABERTA_MATRICULA
CANCELADA
}

Curso o-- Disciplina

Aluno -- Curso

Turma -- Disciplina
Turma --- Professor
Turma ------ Aluno

Disciplina -- Status

@enduml